version: "3"

services:
  server:
    build:
      context: .
    command: bash -c "go get & go build & go run ."
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    environment:
      - MARVEL_PUBLIC_KEY
      - MARVEL_PRIVATE_KEY
      - MARVEL_URL=http://gateway.marvel.com/v1/public

  test:
    build:
      context: .
    command: bash -c "go get -t & go build & go test ./... -v"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MARVEL_PUBLIC_KEY
      - MARVEL_PRIVATE_KEY
      - MARVEL_URL=http://gateway.marvel.com/v1/public

  swag:
    build:
      context: .
    command: bash -c "go install github.com/swaggo/swag/cmd/swag@latest && swag init && rm docs/docs.go"
    working_dir: /app
    volumes:
      - ./:/app
