version: "3"

services:
  server:
    build:
      context: .
    image: marvel
    command: go run .
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - MARVEL_PUBLIC_KEY
      - MARVEL_PRIVATE_KEY
      - MARVEL_URL=http://gateway.marvel.com/v1/public

  updatefile:
    image: marvel
    command: ./warmup.sh
    working_dir: /app/script
    volumes:
      - ./:/app
    environment:
      - MARVEL_PUBLIC_KEY
      - MARVEL_PRIVATE_KEY
      - MARVEL_URL=http://gateway.marvel.com/v1/public

  test:
    image: marvel
    command: go test ./... -v
    working_dir: /app
    environment:
      - MARVEL_PUBLIC_KEY
      - MARVEL_PRIVATE_KEY
      - MARVEL_URL=http://gateway.marvel.com/v1/public

  swag:
    image: marvel
    command: bash -c "go install github.com/swaggo/swag/cmd/swag@latest && swag init && rm docs/docs.go"
    working_dir: /app
    volumes:
      - ./:/app
